main/default/objects/Follow_Up__c/Follow_Up__c.object-meta.xml
<CustomObject>
    <label>Follow-Up</label>
    <nameField>
        <label>Revisit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Follow-Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

deploytoOrg/PatientManagementNew/force-app/main/default/objects/Follow_Up__c/fields/Follow_Up_Time__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Time__c</fullName>
    <label>Follow-Up Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3:30 PM - 3:45 PM</fullName>
            </value>
            <value>
                <fullName>3:45 PM - 4:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM - 4:15 PM</fullName>
            </value>
            <value>
                <fullName>4:15 PM - 4:30 PM</fullName>
            </value>
            <value>
                <fullName>4:30 PM - 4:45 PM</fullName>
            </value>
            <value>
                <fullName>4:45 PM - 5:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM - 5:15 PM</fullName>
            </value>
            <value>
                <fullName>5:15 PM - 5:30 PM</fullName>
            </value>
            <value>
                <fullName>5:30 PM - 5:45 PM</fullName>
            </value>
            <value>
                <fullName>5:45 PM - 6:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

deploytoOrg/PatientManagementNew/force-app/main/default/classes/ClassForNameDateTime.cls
public class ClassForNameDateTime {
    public static void DoctorNameDateAndTime(){
        List <Follow_up__c> follow = new List<Follow_up__c>();
        follow = [Select Follow_Up_Date__c, Follow_Up_Time__c, Previously_Checked_By_Dr__c FROM Follow_Up__c where Follow_Up_Time__c != NULL];
        
        for(Follow_Up__c newFollow : (List<Follow_Up__c >) Trigger.new){
            if(newFollow.Follow_Up_Time__c != Null){
                for(Follow_Up__c oldRecords : follow){
                    if (oldRecords.Follow_Up_Date__c == newFollow.Follow_Up_Date__c && oldRecords.Follow_Up_Time__c == newFollow.Follow_Up_Time__c &&
                        oldRecords.Previously_Checked_By_Dr__c == newFollow.Previously_Checked_By_Dr__c){
                            newFollow.Follow_Up_Time__c.addError ('Follow-Up Time already Selected For this Day');
                        }
                }
            }
        }
    }
}