deploytoOrg/PatientManagementNew/Patient Management/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

deploytoOrg/PatientManagementNew/force-app/main/default/objects/Patient__c/fields/Doctor_Available__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Available__c</fullName>
    <label>Doctor Available</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specialist_Available__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dr. Bhanu Prakash</fullName>
            </value>
            <value>
                <fullName>Dr. Bikash Nepal</fullName>
            </value>
            <value>
                <fullName>Dr. Bilash Gautam</fullName>
            </value>
            <value>
                <fullName>Dr. Bishal Raj</fullName>
            </value>
            <value>
                <fullName>Dr. Gautam Yadav</fullName>
            </value>
            <value>
                <fullName>Dr. Gyanu Prasad</fullName>
            </value>
            <value>
                <fullName>Dr. Himanshu Pradhan</fullName>
            </value>
            <value>
                <fullName>Dr. Hiralal Jadav</fullName>
            </value>
            <value>
                <fullName>Dr. Keshav Bhandari</fullName>
            </value>
            <value>
                <fullName>Dr. Kripa Khadka</fullName>
            </value>
            <value>
                <fullName>Dr. Mahesh Panta</fullName>
            </value>
            <value>
                <fullName>Dr. Menuka Ayer</fullName>
            </value>
            <value>
                <fullName>Dr. Mina Neupane</fullName>
            </value>
            <value>
                <fullName>Dr. Rajesh Karki</fullName>
            </value>
            <value>
                <fullName>Dr. Rohan Dhungel</fullName>
            </value>
            <value>
                <fullName>Dr. Ruben Khatri</fullName>
            </value>
            <value>
                <fullName>Dr. Sagar KC</fullName>
            </value>
            <value>
                <fullName>Dr. Samjeeb Yadav</fullName>
            </value>
            <value>
                <fullName>Dr. Shiv Narayan Yadav</fullName>
            </value>
            <value>
                <fullName>Dr. Sita Jha</fullName>
            </value>
            <value>
                <fullName>Dr. Subekshya Katwal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

deploytoOrg/PatientManagementNew/Patient Management/main/default/classes/ApexClassforAppointmentDoctor.cls
public class ApexClassforAppointmentDoctor {
    public static void AppointDocDateTime(){
        LIST<Patient__c> li = [select id,Select_Appointment_Time__c,Doctor_Available__c, Select_Appointment_Date__c from Patient__c where Select_Appointment_Time__c!= null]; 
    for(Patient__c pat :(LIST<Patient__c>) trigger.new)
    {
        if(pat.Select_Appointment_Time__c != null){
            for(Patient__c existrecord :li)
            {
                if(existrecord.Select_Appointment_Time__c == pat.Select_Appointment_Time__c && existrecord.Doctor_Available__c == pat.Doctor_Available__c && existrecord.Select_Appointment_Date__c == pat.Select_Appointment_Date__c){
                    pat.Select_Appointment_Time__c.adderror('Appoinment Time has already been Selected. Either Change Appointment Date or Time');
                    
                }  
            }       
        }
    }
    }
}